import { v4 as uuid } from "uuid";

import {
    t_shirt_1,
    t_shirt_2,
    t_shirt_3,
    t_shirt_4,
    t_shirt_5,
    shirt_1,
    shirt_2,
    shirt_3,
    shirt_4,
    shirt_5,
    jacket_1,
    jacket_2,
    jacket_3,
    jacket_4,
    jacket_5,
    pant_1,
    pant_2,
    pant_3,
    pant_4,
    pant_5,
    shoes_1,
    shoes_2,
    shoes_3,
    shoes_4,
    shoes_5,
    goggle_1,
    goggle_2,
    goggle_3,
    goggle_4,
    goggle_5
} from "../assets/images/index";



const ProductData = [
    {
        _id: uuid(),
        image: t_shirt_1,
        price: 399,
        MRP: 1999,
        categoryName: "T-shirt",
        productTitle: "Men's premium shirt",
        rating: 5,
        review: "18",
        quantity: 1,
        tag: "New"
    },
    {
        _id: uuid(),
        image: t_shirt_2,
        price: 1199,
        MRP: 1999,
        categoryName: "T-shirt",
        productTitle: "Men's premium shirt",
        rating: 5,
        review: "18",
        quantity: 1,
        tag: "New"
    },
    {
        _id: uuid(),
        image: t_shirt_3,
        price: 2000,
        MRP: 1999,
        categoryName: "T-shirt",
        productTitle: "Men's premium shirt",
        rating: 3,
        review: "18",
        quantity: 1,
        tag: "New"
    },
    {
        _id: uuid(),
        image: t_shirt_4,
        price: 2000,
        MRP: 1999,
        categoryName: "T-shirt",
        productTitle: "Men's premium shirt",
        rating: 3,
        review: "18",
        quantity: 1,
        tag: "New"
    },
    {
        _id: uuid(),
        image: t_shirt_5,
        price: 2000,
        MRP: 1999,
        categoryName: "T-shirt",
        productTitle: "Men's premium shirt",
        rating: 3,
        review: "18",
        quantity: 1,
        tag: "New"
    },
    {
        _id: uuid(),
        image: jacket_1,
        price: 1800,
        MRP: 1999,
        categoryName: "jacket",
        productTitle: "Men's premium jacket",
        rating: 5,
        review: "18",
        quantity: 1,
        tag: "New"
    },
    {
        _id: uuid(),
        image: jacket_2,
        price: 1800,
        MRP: 1999,
        categoryName: "jacket",
        productTitle: "Men's premium jacket",
        rating: 5,
        review: "18",
        quantity: 1,
        tag: "New"
    },
    {
        _id: uuid(),
        image: jacket_3,
        price: 8500,
        MRP: 1999,
        categoryName: "jacket",
        productTitle: "Men's premium jacket",
        rating: 3,
        review: "18",
        quantity: 1,
        tag: "New"
    },
    {
        _id: uuid(),
        image: jacket_4,
        price: 399,
        MRP: 1999,
        categoryName: "jacket",
        productTitle: "Men's premium jacket",
        rating: 3,
        review: "18",
        quantity: 1,
        tag: "New"
    },
    {
        _id: uuid(),
        image: jacket_5,
        price: 1800,
        MRP: 1999,
        categoryName: "jacket",
        productTitle: "Men's premium jacket",
        rating: 3,
        review: "18",
        quantity: 1,
        tag: "New"
    },
    {
        _id: uuid(),
        image: shirt_1,
        price: 5000,
        MRP: 1999,
        categoryName: "shirt",
        productTitle: "Men's premium shirt",
        rating: 1,
        review: "18",
        quantity: 1,
        tag: "New"
    },
    {
        _id: uuid(),
        image: shirt_2,
        price: 5000,
        MRP: 1999,
        categoryName: "shirt",
        productTitle: "Men's premium shirt",
        rating: 1,
        review: "18",
        quantity: 1,
        tag: "New"
    },
    {
        _id: uuid(),
        image: shirt_3,
        price: 1199,
        MRP: 1999,
        categoryName: "shirt",
        productTitle: "Men's premium shirt",
        rating: 3,
        review: "18",
        quantity: 1,
        tag: "New"
    },
    {
        _id: uuid(),
        image: shirt_4,
        price: 1199,
        MRP: 1999,
        categoryName: "shirt",
        productTitle: "Men's premium shirt",
        rating: 3,
        review: "18",
        quantity: 1,
        tag: "New"
    },
    {
        _id: uuid(),
        image: shirt_5,
        price: 1199,
        MRP: 1999,
        categoryName: "shirt",
        productTitle: "Men's premium shirt",
        rating: 5,
        review: "18",
        quantity: 1,
        tag: "New"
    },
    {
        _id: uuid(),
        image: pant_1,
        price: 1199,
        MRP: 1999,
        categoryName: "pant",
        productTitle: "Men's premium pant",
        rating: 3,
        review: "18",
        quantity: 1,
        tag: "New"
    },
    {
        _id: uuid(),
        image: pant_2,
        price: 1199,
        MRP: 1999,
        categoryName: "pant",
        productTitle: "Men's premium pant",
        rating: 3,
        review: "18",
        quantity: 1,
        tag: "New"
    },
    {
        _id: uuid(),
        image: pant_3,
        price: 1199,
        MRP: 1999,
        categoryName: "pant",
        productTitle: "Men's premium pant",
        rating: 3,
        review: "18",
        quantity: 1,
        tag: "New"
    },
    {
        _id: uuid(),
        image: pant_4,
        price: 1199,
        MRP: 1999,
        categoryName: "pant",
        productTitle: "Men's premium pant",
        rating: 3,
        review: "18",
        quantity: 1,
        tag: "New"
    },
    {
        _id: uuid(),
        image: pant_5,
        price: 1199,
        MRP: 1999,
        categoryName: "pant",
        productTitle: "Men's premium pant",
        rating: 3,
        review: "18",
        quantity: 1,
        tag: "New"
    },
    {
        _id: uuid(),
        image: shoes_1,
        price: 2199,
        MRP: 2999,
        categoryName: "shoes",
        productTitle: "Men's premium shoes",
        rating: 3,
        review: "18",
        quantity: 1,
        tag: "New"
    },
    {
        _id: uuid(),
        image: shoes_2,
        price: 2199,
        MRP: 2999,
        categoryName: "shoes",
        productTitle: "Men's premium shoes",
        rating: 3,
        review: "18",
        quantity: 1,
        tag: "New"
    },
    {
        _id: uuid(),
        image: shoes_3,
        price: 2199,
        MRP: 2999,
        categoryName: "shoes",
        productTitle: "Men's premium shoes",
        rating: 3,
        review: "18",
        quantity: 1,
        tag: "New"
    },
    {
        _id: uuid(),
        image: shoes_4,
        price: 2199,
        MRP: 2999,
        categoryName: "shoes",
        productTitle: "Men's premium shoes",
        rating: 3,
        review: "18",
        quantity: 1,
        tag: "New"
    },
    {
        _id: uuid(),
        image: shoes_5,
        price: 2199,
        MRP: 2999,
        categoryName: "shoes",
        productTitle: "Men's premium shoes",
        rating: 3,
        review: "18",
        quantity: 1,
        tag: "New"
    },
    {
        _id: uuid(),
        image: goggle_1,
        price: 2199,
        MRP: 2999,
        categoryName: "goggles",
        productTitle: "Men's premium goggle",
        rating: 3,
        review: "18",
        quantity: 1,
        tag: "New"
    },
    {
        _id: uuid(),
        image: goggle_2,
        price: 2199,
        MRP: 2999,
        categoryName: "goggles",
        productTitle: "Men's premium goggle",
        rating: 3,
        review: "18",
        quantity: 1,
        tag: "New"
    },
    {
        _id: uuid(),
        image: goggle_3,
        price: 2199,
        MRP: 2999,
        categoryName: "goggles",
        productTitle: "Men's premium goggle",
        rating: 3,
        review: "18",
        quantity: 1,
        tag: "New"
    },
    {
        _id: uuid(),
        image: goggle_4,
        price: 219,
        MRP: 2999,
        categoryName: "goggles",
        productTitle: "Men's premium goggle",
        rating: 3,
        review: "18",
        quantity: 1,
        tag: "New"
    },
    {
        _id: uuid(),
        image: goggle_5,
        price: 2199,
        MRP: 2999,
        categoryName: "goggles",
        productTitle: "Men's premium goggle",
        rating: 3,
        review: "18",
        quantity: 1,
        tag: "New"
    }
    
]

export default ProductData